#Thanks to Andy South <southandy@gmail.com> for rworldmap,
#the package that makes this script possible!
#http://cran.r-project.org/web/packages/rworldmap/
library(rworldmap)
#Map coloring generated by Erich Neuwirth's RColorBrewer
#http://cran.r-project.org/web/packages/RColorBrewer
library(RColorBrewer)

#Load in the current dataset
chipArtistData <- read.csv("C:\\Users\\mansellw\\Documents\\Projects\\ChipWINData\\ChiptunersByCountry.csv")

#Join Data to Map
artMapData <- joinCountryData2Map(chipArtistData, 
                                  nameJoinColumn="Country",
                                  joinCode="NAME")

#Prep an SVG Device for exporting the plot to be cleaned up in Inkscape or Illustrator
#Width and Height are interpreted in inches
svg("C:\\Users\\mansellw\\Documents\\Projects\\ChipWINData\\chipArtistDensity.svg", width=16,height=9)

#Generate color palette to use on map
cAPalette <- brewer.pal(8,'YlOrRd')

#Plot the map
cAMapParams <- mapCountryData(artMapData, 
                nameColumnToPlot="Count", 
                catMethod=c(1,2,10,20,27,32,38,85,437),
                colourPalette=cAPalette,
                borderCol = 'black',
                oceanCol = 'lightblue',
                missingCountryCol = 'grey',
                mapTitle = 'Global Chiptune Artist Density',
                addLegend=FALSE,
                numCats=9)

#This call allows for some configuration of the Legend after the map is generated.
do.call(addMapLegend, c(cAMapParams,
                        legendLabels='all',legendWidth=0.5, legendMar = 2))

#Close the visualization Device to finish exporting data and save file.
dev.off()
